### ISSUE TITLE
Debian package uploads fail

### ISSUE THREAD

**Issue by stagrlee** [rerun-modules/bintray#2]
A bunch of extra paramenters are needed to upload debian packages to APT repos....

```
unexpected response code: {"message":"Unable to upload files: Debian distribution, component and architecture must be specified"} 
```

**Comment by stagrlee** [comment]
Got a fix coded

**Comment by stagrlee** [comment]
Alex - check implementation out.  New syntax to upload/publish in one step implemented as well as added bebian meta-data.

**Comment by ahonor** [comment]
Nice

**Comment by stagrlee** [comment]
in CI/CD and fixed
